language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

env:
    globals:
        - deps=no

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
    - if [ "$deps" = "no" ]; then composer install; fi;

script: |
    if [[ $TRAVIS_PHP_VERSION = 7.* || $TRAVIS_PHP_VERSION = nightly ]]; then
        SYMFONY_PHPUNIT_VERSION=6.1 ./vendor/bin/simple-phpunit
    else
        ./vendor/bin/simple-phpunit
    fi

matrix:
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=low
        - php: 7.0
        - php: 7.1
        - php: 7.2
    fast_finish: true
